apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-bedrock
  namespace: k8sgpt-operator-system
spec:
  version: v0.4.30
  ai:
    enabled: true
    model: us.amazon.nova-lite-v1:0
    backend: amazonbedrock
    region: us-east-1
  noCache: false
  filters:
    - Pod
    - Deployment
    - Service
    - ReplicaSet
  extraOptions:
    serviceAccountIRSA: arn:aws:iam::660235343049:role/eks-aiops-cluster-k8sgpt-bedrock-role