apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgpt-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Anish1614/eks-aiops-k8sgpt-argocd.git
    targetRevision: HEAD
    path: helm/k8sgpt/active
  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgpt-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true